<?php
/*
 * Copyright (C) 2012 NetLife Inc. All Rights Reserved.
 * http://www.netlife-web.com/
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

require(dirname(__FILE__)."/WordpressConvertSetting.php");
require(dirname(__FILE__)."/".WORDPRESS_CONVERT_CONTENT_MANAGER.".php");

/**
 * HTMLをWordpressテンプレートに変換するプラグインのメインクラス
 *
 * @package WordpressConvert
 * @author Naohisa Minagawa
 * @version 1.0
 */
class WordpressConvert {
	/**
	 * Initial
	 * @return void
	 */
	public static function init(){
		// 環境のバージョンチェック
		if( version_compare( PHP_VERSION, '5.3.0', '<' ) )
			trigger_error( __("PHP 5.3 or later is required for this plugin."), E_USER_ERROR );
		
		// 初期化処理
		add_action( 'admin_menu', array( WORDPRESS_CONVERT_SETTING_CLASS, 'init' ) );
	}
	
	/**
	 * 変換処理を必要に応じて実行する。
	 */
	public static function execute(){
		$contentManagerClass = WORDPRESS_CONVERT_CONTENT_MANAGER;
		$contentManager = new $contentManagerClass(get_option("wordpress_convert_ftp_login_id"), get_option("wordpress_convert_ftp_password"), get_option("wordpress_convert_base_dir"));
		$filename = $contentManager->getContentHome()."/style.css";
		$themeFile = $contentManager->getThemeFile($filename);
		$info = pathinfo($themeFile);
		if(!is_dir($info["dirname"])){
			mkdir($info["dirname"], 0755, true);
		}
		if(($fp = fopen($themeFile, "w+")) !== FALSE){
			fwrite($fp, "/* \r\n");
			fwrite($fp, "Theme Name: ".WORDPRESS_CONVERT_THEME_NAME."\r\n");
			fwrite($fp, "Description: Converted Theme by Wordpress Converter\r\n");
			fwrite($fp, "Author: NetLife Inc.\r\n");
			fwrite($fp, "Author URI: http://www.netlife-web.com/\r\n");
			fwrite($fp, "Version: 1.0\r\n");
			fwrite($fp, "\r\n");
			fwrite($fp, "This themes was generated by Wordpress Converter Plugin.\r\n");
			fwrite($fp, "Theme can not use except for servers which we select.\r\n");
			fwrite($fp, "In case, theme uses others, you may spent extra fee.\r\n");
			fwrite($fp, "\r\n");
			fwrite($fp, "*/\r\n");
			fclose($fp);
		}
		
		$files = $contentManager->getList();
		foreach($files as $filename){
			if($contentManager->isUpdated($filename)){
				$themeFile = $contentManager->getThemeFile($filename);
				$info = pathinfo($themeFile);
				if(!is_dir($info["dirname"])){
					mkdir($info["dirname"], 0755, true);
				}
				if(($fp = fopen($themeFile, "w+")) !== FALSE){
					fwrite($fp, $contentManager->getContent($filename));
					fclose($fp);
				}
			}
		}
	}

	function install(){
		// インストール時の処理
	}

	function uninstall(){
		// アンインストール時の処理
	}


}
?>